# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#82aaff" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#ff757f", bold = true, italic = true, underline = true }
find_position = { fg = "#c099ff", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#c3e88d", bg = "#c3e88d" }
marker_cut      = { fg = "#ffc777", bg = "#ff757f" }
marker_marked   = { fg = "#82aaff", bg = "#7dcfff" }
marker_selected = { fg = "#ffc777", bg = "#ffc777" }

# Count
count_copied   = { fg = "#222436", bg = "#c3e88d" }
count_cut      = { fg = "#222436", bg = "#ffc777" }
count_selected = { fg = "#222436", bg = "#82aaff" }

# Border
border_symbol = "│"
border_style  = { fg = "#4e5579" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#363b54", bg = "#82aaff", bold = true }
inactive = { fg = "#82aaff", bg = "#363b54" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#363b54", bg = "#82aaff", bold = true }
normal_alt  = { fg = "#82aaff", bg = "#363b54" }

# Select mode
select_main = { fg = "#363b54", bg = "#c3e88d", bold = true }
select_alt  = { fg = "#82aaff", bg = "#363b54" }

# Unset mode
unset_main = { fg = "#363b54", bg = "#c099ff", bold = true }
unset_alt  = { fg = "#82aaff", bg = "#363b54" }

# : }}}


# : Status bar {{{

[status]
overall = { fg = "#82aaff" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }


# Progress
progress_label = { fg = "#363b54", bold = true }
progress_normal = { fg = "#82aaff", bg = "#363b54" }
progress_error = { fg = "#ff757f", bg = "#363b54" }

# Permissions
perm_sep   = { fg = "#82aaff" }
perm_type  = { fg = "#c3e88d" }
perm_read  = { fg = "#ffc777" }
perm_write = { fg = "#ff757f" }
perm_exec  = { fg = "#c099ff" }


# : }}}

# : Pick {{{

[pick]
border = { fg = "#82aaff" }
active = { fg = "#c099ff", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#82aaff" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#82aaff" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#82aaff" }
title   = {}
hovered = { fg = "#c099ff", underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#4e5579" }
cand            = { fg = "#c3e88d" }
rest            = { fg = "#9aa5ce" }
desc            = { fg = "#c099ff" }
separator       = "  "
separator_style = { fg = "#626880" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#c3e88d" }
run     = { fg = "#c099ff" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#222436", bg = "#9aa5ce" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#c3e88d" }
title_warn  = { fg = "#ff757f" }
title_error = { fg = "#ffc777" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#ffc777" },

	# Media
	{ mime = "video/*", fg = "#ff757f" },
	{ mime = "audio/*", fg = "#ff757f" },

	# Archives
	{ mime = "application/zip",             fg = "#c099ff" },
	{ mime = "application/x-tar",           fg = "#c099ff" },
	{ mime = "application/x-bzip*",         fg = "#c099ff" },
	{ mime = "application/x-bzip2",         fg = "#c099ff" },
	{ mime = "application/x-7z-compressed", fg = "#c099ff" },
	{ mime = "application/x-rar",           fg = "#c099ff" },
	{ mime = "application/x-xz",            fg = "#c099ff" },

	# Documents
	{ mime = "application/doc",        fg = "#c3e88d" },
	{ mime = "application/epub+zip",   fg = "#c3e88d" },
	{ mime = "application/pdf",        fg = "#c3e88d" },
	{ mime = "application/rtf",        fg = "#c3e88d" },
	{ mime = "application/vnd.*",      fg = "#c3e88d" },

	# Fallback
	{ name = "*", fg = "#c8d3f5" },
	{ name = "*/", fg = "#82aaff" }
]

# : }}}
