# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#828bb8" }

# Hovered
hovered = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#ffc777", bold = true, italic = true, underline = true }
find_position = { fg = "#fca7ea", bg = "reset", bold = true, italic = true }

# Marker
marker_copied = { fg = "#c3e88d", bg = "#c3e88d" }
marker_cut = { fg = "#ff757f", bg = "#ff757f" }
marker_marked = { fg = "#0db9d7", bg = "#0db9d7" }
marker_selected = { fg = "#ffc777", bg = "#ffc777" }

# Count
count_copied = { fg = "#1e2030", bg = "#c3e88d" }
count_cut = { fg = "#1e2030", bg = "#ff757f" }
count_selected = { fg = "#1e2030", bg = "#ffc777" }

# Border
border_symbol = "│"
border_style = { fg = "#589ed7" }

# : }}}


# : Tabs {{{

[tabs]
active = { fg = "#1e2030", bg = "#82aaff", bold = true }
inactive = { fg = "#82aaff", bg = "#3b4261" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#1e2030", bg = "#82aaff", bold = true }
normal_alt = { fg = "#82aaff", bg = "#3b4261" }

# Select mode
select_main = { fg = "#1e2030", bg = "#c099ff", bold = true }
select_alt = { fg = "#c099ff", bg = "#3b4261" }

# Unset mode
unset_main = { fg = "#1e2030", bg = "#fca7ea", bold = true }
unset_alt = { fg = "#fca7ea", bg = "#3b4261" }

# : }}}


# : Status bar {{{

[status]
overall = { fg = "#c8d3f5", bg = "#1e2030" }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep = { fg = "#444a73" }
perm_type = { fg = "#82aaff" }
perm_read = { fg = "#ffc777" }
perm_write = { fg = "#ff757f" }
perm_exec = { fg = "#c3e88d" }

# Progress
progress_label = { fg = "#c8d3f5", bold = true }
progress_normal = { fg = "#3e68d7", bg = "#2f334d" }
progress_error = { fg = "#c53b53", bg = "#2f334d" }

# : }}}


# : Pick {{{

[pick]
border = { fg = "#0db9d7" }
active = { fg = "#fca7ea", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "#0db9d7" }
title = {}
value = { fg = "#fca7ea" }
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#0db9d7" }

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#0db9d7" }
title = {}
hovered = { fg = "#fca7ea", bold = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#1e2030" }
cand = { fg = "#0db9d7" }
rest = { fg = "#82aaff" }
desc = { fg = "#c099ff" }
separator = " ➜ "
separator_style = { fg = "#636da6" }

# : }}}


# : Confirm {{{

[confirm]
border = { fg = "#0db9d7" }
title = { fg = "#589ed7" }
content = {}
list = {}
btn_yes = { bg = "#2d3f76" }
btn_no = {}
btn_labels = ["  [Y]es  ", "  (N)o  "]

# : }}}


# : Help {{{

[help]
on = { fg = "#c3e88d" }
run = { fg = "#c099ff" }
desc = { fg = "#86e1fc" }
hovered = { reversed = true, bold = true }
footer = { fg = "#c8d3f5", bg = "#222436" }

# : }}}


# : Spotter {{{

[spot]
border = { fg = "#589ed7" }
title = { fg = "#589ed7" }
tbl_col = { fg = "#0db9d7" }
tbl_cell = { fg = "#fca7ea", bg = "#2f334d" }

# : }}}


# : Notification {{{

[notify]
title_info = { fg = "#0db9d7" }
title_warn = { fg = "#ffc777" }
title_error = { fg = "#c53b53" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Image
    { mime = "image/*", fg = "#ffc777" },
    # Media
    { mime = "{audio,video}/*", fg = "#c099ff" },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#ff757f" },
    # Document
    { mime = "application/{pdf,doc,rtf}", fg = "#86e1fc" },
    # Virtual file system
    { mime = "vfs/{absent,stale}", fg = "#ff757f" },
    # Fallback
    { url = "*", fg = "#c8d3f5" },
    { url = "*/", fg = "#82aaff" },
]

# : }}}
